In [1]:
# import lib
import pandas as pd
import numpy as np
import seaborn as sns
from matplotlib import pyplot as plt 
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, RobustScaler, StandardScaler, MinMaxScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB

In [5]:
df_train = pd.read_csv("E:\\ML\\AISS\\patient_stay_2_1310\\dataset\\train_data.csv")
df_test = pd.read_csv("E:\\ML\\AISS\\patient_stay_2_1310\\dataset\\test_data.csv")
print("train ",df_train.shape, " test ", df_test.shape)
df_train.head(2)

train  (318438, 18)  test  (137057, 17)


case_id  Hospital_code Hospital_type_code  City_Code_Hospital  \
0        1              8                  c                   3   
1        2              2                  c                   5   

  Hospital_region_code  Available Extra Rooms in Hospital    Department  \
0                    Z                                  3  radiotherapy   
1                    Z                                  2  radiotherapy   

  Ward_Type Ward_Facility_Code  Bed Grade  patientid  City_Code_Patient  \
0         R                  F        2.0      31397                7.0   
1         S                  F        2.0      31397                7.0   

  Type of Admission Severity of Illness  Visitors with Patient    Age  \
0         Emergency             Extreme                      2  51-60   
1            Trauma             Extreme                      2  51-60   

   Admission_Deposit   Stay  
0             4911.0   0-10  
1             5954.0  41-50

In [6]:
df_train.Stay.unique()

array(['0-10', '41-50', '31-40', '11-20', '51-60', '21-30', '71-80',
       'More than 100 Days', '81-90', '61-70', '91-100'], dtype=object)

In [7]:
df_train.corr()

case_id  Hospital_code  \
case_id                            1.000000      -0.043023   
Hospital_code                     -0.043023       1.000000   
City_Code_Hospital                -0.011352       0.128294   
Available Extra Rooms in Hospital  0.042580      -0.059638   
Bed Grade                          0.013702      -0.013739   
patientid                         -0.004150       0.002291   
City_Code_Patient                  0.065196      -0.015530   
Visitors with Patient              0.001309      -0.028500   
Admission_Deposit                 -0.045972       0.045446   

                                   City_Code_Hospital  \
case_id                                     -0.011352   
Hospital_code                                0.128294   
City_Code_Hospital                           1.000000   
Available Extra Rooms in Hospital           -0.045771   
Bed Grade                                   -0.049309   
patientid                                    0.000750   
City_Code_Patient                           -0.023988   
Visitors with Patient                        0.018184   
Admission_Deposit                           -0.034455   

                                   Available Extra Rooms in Hospital  \
case_id                                                     0.042580   
Hospital_code                                              -0.059638   
City_Code_Hospital                                         -0.045771   
Available Extra Rooms in Hospital                           1.000000   
Bed Grade                                                  -0.115868   
patientid                                                   0.000921   
City_Code_Patient                                          -0.009681   
Visitors with Patient                                       0.096714   
Admission_Deposit                                          -0.143739   

                                   Bed Grade  patientid  City_Code_Patient  \
case_id                             0.013702  -0.004150           0.065196   
Hospital_code                      -0.013739   0.002291          -0.015530   
City_Code_Hospital                 -0.049309   0.000750          -0.023988   
Available Extra Rooms in Hospital  -0.115868   0.000921          -0.009681   
Bed Grade                           1.000000   0.001645          -0.008105   
patientid                           0.001645   1.000000           0.002002   
City_Code_Patient                  -0.008105   0.002002           1.000000   
Visitors with Patient               0.088945   0.006889          -0.012074   
Admission_Deposit                   0.073833  -0.000877           0.025837   

                                   Visitors with Patient  Admission_Deposit  
case_id                                         0.001309          -0.045972  
Hospital_code                                  -0.028500           0.045446  
City_Code_Hospital                              0.018184          -0.034455  
Available Extra Rooms in Hospital               0.096714          -0.143739  
Bed Grade                                       0.088945           0.073833  
patientid                                       0.006889          -0.000877  
City_Code_Patient                              -0.012074           0.025837  
Visitors with Patient                           1.000000          -0.150358  
Admission_Deposit                              -0.150358           1.000000

In [8]:
label_encoder = preprocessing.LabelEncoder()

In [9]:
print(df_train.Stay.unique())
df_train['Stay'] = label_encoder.fit_transform(df_train['Stay'])
print(df_train.Stay.unique())
stay_train = df_train.Stay

['0-10' '41-50' '31-40' '11-20' '51-60' '21-30' '71-80'
 'More than 100 Days' '81-90' '61-70' '91-100']
[ 0  4  3  1  5  2  7 10  8  6  9]


In [10]:
X = df_train.drop("Stay", axis=1)
y = df_test
data = pd.concat([X,y])

In [11]:
print(data.shape)
data.head(2)

(455495, 17)


case_id  Hospital_code Hospital_type_code  City_Code_Hospital  \
0        1              8                  c                   3   
1        2              2                  c                   5   

  Hospital_region_code  Available Extra Rooms in Hospital    Department  \
0                    Z                                  3  radiotherapy   
1                    Z                                  2  radiotherapy   

  Ward_Type Ward_Facility_Code  Bed Grade  patientid  City_Code_Patient  \
0         R                  F        2.0      31397                7.0   
1         S                  F        2.0      31397                7.0   

  Type of Admission Severity of Illness  Visitors with Patient    Age  \
0         Emergency             Extreme                      2  51-60   
1            Trauma             Extreme                      2  51-60   

   Admission_Deposit  
0             4911.0  
1             5954.0

In [12]:
# rename columns
original_col = data.columns
new_col = ['case_id','Hospital_code','Hospital_type_code','City_Code_Hospital','Hospital_region_code','Available_Extra_Rooms_in_Hospital','Department','Ward_Type','Ward_Facility_Code','Bed_Grade','patientid','City_Code_Patient','Type_of_Admission','Severity_of_Illness','Visitors_with_Patient','Age','Admission_Deposit']                                                                                                               
data =data.rename(columns=dict(zip(original_col, new_col)))
print(data.shape)
#print(data.head())

(455495, 17)


In [13]:
data.isnull().sum()

case_id                                 0
Hospital_code                           0
Hospital_type_code                      0
City_Code_Hospital                      0
Hospital_region_code                    0
Available_Extra_Rooms_in_Hospital       0
Department                              0
Ward_Type                               0
Ward_Facility_Code                      0
Bed_Grade                             148
patientid                               0
City_Code_Patient                    6689
Type_of_Admission                       0
Severity_of_Illness                     0
Visitors_with_Patient                   0
Age                                     0
Admission_Deposit                       0
dtype: int64

In [14]:
print(data.Bed_Grade.mode())
data.Bed_Grade = data.Bed_Grade.fillna(2.0)

print(data.City_Code_Patient.mode())
data.City_Code_Patient = data.City_Code_Patient.fillna(8.0)

0    2.0
dtype: float64
0    8.0
dtype: float64


In [15]:
print(data.isnull().sum())
data.shape

case_id                              0
Hospital_code                        0
Hospital_type_code                   0
City_Code_Hospital                   0
Hospital_region_code                 0
Available_Extra_Rooms_in_Hospital    0
Department                           0
Ward_Type                            0
Ward_Facility_Code                   0
Bed_Grade                            0
patientid                            0
City_Code_Patient                    0
Type_of_Admission                    0
Severity_of_Illness                  0
Visitors_with_Patient                0
Age                                  0
Admission_Deposit                    0
dtype: int64


(455495, 17)

In [16]:
fig_dims = (30, 30)
fig, ax = plt.subplots(figsize=fig_dims)
hist = data.hist(bins=20, ax=ax) 
plt.savefig("hist.png")
#plt.show()
plt.close()

c:\users\sheetal\appdata\local\programs\python\python37\lib\site-packages\IPython\core\interactiveshell.py:3296: UserWarning: To output multiple subplots, the figure containing the passed axes is being cleared
  exec(code_obj, self.user_global_ns, self.user_ns)


In [17]:
data.dtypes

case_id                                int64
Hospital_code                          int64
Hospital_type_code                    object
City_Code_Hospital                     int64
Hospital_region_code                  object
Available_Extra_Rooms_in_Hospital      int64
Department                            object
Ward_Type                             object
Ward_Facility_Code                    object
Bed_Grade                            float64
patientid                              int64
City_Code_Patient                    float64
Type_of_Admission                     object
Severity_of_Illness                   object
Visitors_with_Patient                  int64
Age                                   object
Admission_Deposit                    float64
dtype: object

Outliers present in 

        City_Code_Patient 
        Available_Extra_Rooms_in_Hospital 
        Visitors_with_Patient
        admission_deposit

In [18]:
print(data.shape)
data.head(3)

(455495, 17)


case_id  Hospital_code Hospital_type_code  City_Code_Hospital  \
0        1              8                  c                   3   
1        2              2                  c                   5   
2        3             10                  e                   1   

  Hospital_region_code  Available_Extra_Rooms_in_Hospital    Department  \
0                    Z                                  3  radiotherapy   
1                    Z                                  2  radiotherapy   
2                    X                                  2    anesthesia   

  Ward_Type Ward_Facility_Code  Bed_Grade  patientid  City_Code_Patient  \
0         R                  F        2.0      31397                7.0   
1         S                  F        2.0      31397                7.0   
2         S                  E        2.0      31397                7.0   

  Type_of_Admission Severity_of_Illness  Visitors_with_Patient    Age  \
0         Emergency             Extreme                      2  51-60   
1            Trauma             Extreme                      2  51-60   
2            Trauma             Extreme                      2  51-60   

   Admission_Deposit  
0             4911.0  
1             5954.0  
2             4745.0

In [19]:
data.dtypes

case_id                                int64
Hospital_code                          int64
Hospital_type_code                    object
City_Code_Hospital                     int64
Hospital_region_code                  object
Available_Extra_Rooms_in_Hospital      int64
Department                            object
Ward_Type                             object
Ward_Facility_Code                    object
Bed_Grade                            float64
patientid                              int64
City_Code_Patient                    float64
Type_of_Admission                     object
Severity_of_Illness                   object
Visitors_with_Patient                  int64
Age                                   object
Admission_Deposit                    float64
dtype: object

In [20]:
fig_dims = (50, 50)
fig, ax = plt.subplots(figsize=fig_dims)
hist = data.hist(bins=20, ax=ax) 
plt.savefig("hist_after_scale.png")
#plt.show()
plt.close()

In [21]:
print(data.shape)
data.head(1)

(455495, 17)


case_id  Hospital_code Hospital_type_code  City_Code_Hospital  \
0        1              8                  c                   3   

  Hospital_region_code  Available_Extra_Rooms_in_Hospital    Department  \
0                    Z                                  3  radiotherapy   

  Ward_Type Ward_Facility_Code  Bed_Grade  patientid  City_Code_Patient  \
0         R                  F        2.0      31397                7.0   

  Type_of_Admission Severity_of_Illness  Visitors_with_Patient    Age  \
0         Emergency             Extreme                      2  51-60   

   Admission_Deposit  
0             4911.0

In [22]:
scaler = RobustScaler()
data[["Hospital_code","City_Code_Hospital","Available_Extra_Rooms_in_Hospital","Bed_Grade","City_Code_Patient","Visitors_with_Patient","Admission_Deposit"]] =scaler.fit_transform(data[["Hospital_code","City_Code_Hospital","Available_Extra_Rooms_in_Hospital","Bed_Grade","City_Code_Patient","Visitors_with_Patient","Admission_Deposit"]])
#"Hospital_code","City_Code_Hospital","Available_Extra_Rooms_in_Hospital","Bed_Grade","City_Code_Patient","Visitors_with_Patient","Admission_Deposit""Hospital_code","City_Code_Hospital","Available_Extra_Rooms_in_Hospital","Bed_Grade","City_Code_Patient","Visitors_with_Patient","Admission_Deposit"
#"Hospital_code","City_Code_Hospital","Available_Extra_Rooms_in_Hospital","Bed_Grade","City_Code_Patient","Visitors_with_Patient","Admission_Deposit"

In [23]:
print(data.shape)
data.head(1)

(455495, 17)


case_id  Hospital_code Hospital_type_code  City_Code_Hospital  \
0        1      -0.733333                  c                -0.4   

  Hospital_region_code  Available_Extra_Rooms_in_Hospital    Department  \
0                    Z                                0.0  radiotherapy   

  Ward_Type Ward_Facility_Code  Bed_Grade  patientid  City_Code_Patient  \
0         R                  F       -1.0      31397              -0.25   

  Type_of_Admission Severity_of_Illness  Visitors_with_Patient    Age  \
0         Emergency             Extreme                   -0.5  51-60   

   Admission_Deposit  
0           0.141687

In [25]:
# Encode labels in column 'Department'.
data["case_id"]= label_encoder.fit_transform(data["case_id"])
data["patientid"]= label_encoder.fit_transform(data["patientid"])
data['Hospital_code']= label_encoder.fit_transform(data['Hospital_code']) 
data['Hospital_type_code']= label_encoder.fit_transform(data['Hospital_type_code'])
data['City_Code_Hospital']= label_encoder.fit_transform(data['City_Code_Hospital']) 
#data['Hospital_region_code']= label_encoder.fit_transform(data['Hospital_region_code']) 
#data['Available_Extra_Rooms_in_Hospita']= label_encoder.fit_transform(data['Available_Extra_Rooms_in_Hospital']) 
data['Department']= label_encoder.fit_transform(data['Department']) 
data['Ward_Type']= label_encoder.fit_transform(data['Ward_Type']) 
data['Ward_Facility_Code']= label_encoder.fit_transform(data['Ward_Facility_Code']) 
data['Type_of_Admission']= label_encoder.fit_transform(data['Type_of_Admission']) 
data['Severity_of_Illness']= label_encoder.fit_transform(data['Severity_of_Illness']) 
data['Visitors_with_Patient']= label_encoder.fit_transform(data['Visitors_with_Patient']) 
data['Age']= label_encoder.fit_transform(data['Age'])



In [26]:
print(data.shape)
data.head(3)

(455495, 17)


case_id  Hospital_code  Hospital_type_code  City_Code_Hospital  \
0        0              7                   2                   2   
1        1              1                   2                   4   
2        2              9                   4                   0   

  Hospital_region_code  Available_Extra_Rooms_in_Hospital  Department  \
0                    Z                                0.0           3   
1                    Z                               -0.5           3   
2                    X                               -0.5           1   

   Ward_Type  Ward_Facility_Code  Bed_Grade  patientid  City_Code_Patient  \
0          2                   5       -1.0      31396              -0.25   
1          3                   5       -1.0      31396              -0.25   
2          3                   4       -1.0      31396              -0.25   

   Type_of_Admission  Severity_of_Illness  Visitors_with_Patient  Age  \
0                  0                    0                      2    5   
1                  1                    0                      2    5   
2                  1                    0                      2    5   

   Admission_Deposit  
0           0.141687  
1           0.995905  
2           0.005733

In [27]:
data.describe()

case_id  Hospital_code  Hospital_type_code  City_Code_Hospital  \
count  455495.00000  455495.000000       455495.000000       455495.000000   
mean   227747.00000      17.326335            1.256501            3.592349   
std    131490.22477       8.634036            1.532773            2.806344   
min         0.00000       0.000000            0.000000            0.000000   
25%    113873.50000      10.000000            0.000000            1.000000   
50%    227747.00000      18.000000            1.000000            4.000000   
75%    341620.50000      25.000000            2.000000            6.000000   
max    455494.00000      31.000000            6.000000           10.000000   

       Available_Extra_Rooms_in_Hospital     Department      Ward_Type  \
count                      455495.000000  455495.000000  455495.000000   
mean                            0.098070       1.944024       1.888087   
std                             0.583497       0.561536       0.804688   
min                            -1.500000       0.000000       0.000000   
25%                            -0.500000       2.000000       1.000000   
50%                             0.000000       2.000000       2.000000   
75%                             0.500000       2.000000       2.000000   
max                            10.500000       4.000000       5.000000   

       Ward_Facility_Code      Bed_Grade      patientid  City_Code_Patient  \
count       455495.000000  455495.000000  455495.000000      455495.000000   
mean             3.286956      -0.371785   65785.793563          -0.184871   
std              1.689726       0.871929   37968.830850           1.181183   
min              0.000000      -2.000000       0.000000          -1.750000   
25%              2.000000      -1.000000   32873.000000          -1.000000   
50%              4.000000       0.000000   65734.000000           0.000000   
75%              5.000000       0.000000   98575.500000           0.000000   
max              5.000000       1.000000  131623.000000           7.500000   

       Type_of_Admission  Severity_of_Illness  Visitors_with_Patient  \
count      455495.000000        455495.000000          455495.000000   
mean            0.782867             1.374033               3.283887   
std             0.689184             0.768535               1.763101   
min             0.000000             0.000000               0.000000   
25%             0.000000             1.000000               2.000000   
50%             1.000000             2.000000               3.000000   
75%             1.000000             2.000000               4.000000   
max             2.000000             2.000000              28.000000   

                 Age  Admission_Deposit  
count  455495.000000      455495.000000  
mean        4.126757           0.114197  
std         1.889698           0.888601  
min         0.000000          -2.406224  
25%         3.000000          -0.453726  
50%         4.000000           0.000000  
75%         5.000000           0.546274  
max         9.000000           5.882064

In [28]:
data.shape

(455495, 17)

In [29]:
data = data.drop("Hospital_region_code", axis=1)
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 455495 entries, 0 to 137056
Data columns (total 16 columns):
case_id                              455495 non-null int64
Hospital_code                        455495 non-null int64
Hospital_type_code                   455495 non-null int64
City_Code_Hospital                   455495 non-null int64
Available_Extra_Rooms_in_Hospital    455495 non-null float64
Department                           455495 non-null int64
Ward_Type                            455495 non-null int64
Ward_Facility_Code                   455495 non-null int64
Bed_Grade                            455495 non-null float64
patientid                            455495 non-null int64
City_Code_Patient                    455495 non-null float64
Type_of_Admission                    455495 non-null int64
Severity_of_Illness                  455495 non-null int64
Visitors_with_Patient                455495 non-null int64
Age                                  455495 non-null int6

### preprocessing of df (train_data) ends here

In [30]:
data_train = data.iloc[:318430]
data_test = data.iloc[318430:]
data.head(1)

case_id  Hospital_code  Hospital_type_code  City_Code_Hospital  \
0        0              7                   2                   2   

   Available_Extra_Rooms_in_Hospital  Department  Ward_Type  \
0                                0.0           3          2   

   Ward_Facility_Code  Bed_Grade  patientid  City_Code_Patient  \
0                   5       -1.0      31396              -0.25   

   Type_of_Admission  Severity_of_Illness  Visitors_with_Patient  Age  \
0                  0                    0                      2    5   

   Admission_Deposit  
0           0.141687

In [31]:
X = data_train.values
test = data_test.values
y = stay_train.values


In [32]:
# Instantiate model and fit to data
clf = RandomForestClassifier(n_estimators = 50)
clf.fit(X, y)

RandomForestClassifier(n_estimators=50)

In [33]:
# Make predictions and store in 'Survived' column of df_test
Y_pred = clf.predict(test)
df_test['Stay'] = Y_pred

In [34]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.33, random_state=42,stratify=y)
classifier = RandomForestClassifier(n_estimators = 50)
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

print("\n\nConfusion Matrix: \n\n", confusion_matrix(y_test, y_pred))
print ("\n\nAccuracy : \n\n", accuracy_score(y_test,y_pred)*100)




Confusion Matrix: 

 [[ 1334  3559  2663   197     7    26     0     2     0     1     0]
 [ 1002 12436  9847  1628    31   801     4    23     4     2     8]
 [  749  8981 17177  1374    52   446     4    19    32     2    36]
 [  399  3542  6467  4634    37  2964     0    76    36     9    39]
 [  146   937  2007   421    37   275     1    10     9     5    27]
 [  156   969  1496  2848    23  5551     5   164   198     5   141]
 [   34   160   406   116     5   134    15     9     6     0    21]
 [   43   224   290   734     2  1566     2   260    42     5   216]
 [   14    65    68   222     4   724     0    16   354     2   128]
 [    7    53    79   173     1   388     1    24    15    68   103]
 [   34    66    97   168     1   630     1    65   126     4  1013]]


Accuracy : 

 40.80411095779607


In [35]:
classifier = RandomForestClassifier(n_estimators = 50)
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

In [36]:
# calculate accuracy

from sklearn.metrics import confusion_matrix, accuracy_score, classification_report


print("\n\nConfusion Matrix: \n\n", confusion_matrix(y_test, y_pred))
print ("\n\nAccuracy : \n\n", accuracy_score(y_test,y_pred)*100)
print("\n\nReport : \n\n", classification_report(y_test, y_pred))



Confusion Matrix: 

 [[ 1329  3565  2656   206     7    24     1     1     0     0     0]
 [ 1038 12548  9731  1596    28   793     4    30     6     1    11]
 [  744  9136 17019  1349    71   460     4    15    43     3    28]
 [  403  3556  6472  4631    39  2928     5    88    27     9    45]
 [  138   894  2041   448    34   265     1    16     7     4    27]
 [  165   956  1489  2890    21  5517     5   171   195    12   135]
 [   34   172   403   115     3   127    17     7     9     1    18]
 [   51   223   304   726     9  1564     2   245    43     8   209]
 [   18    68    73   191     2   739     0    15   359     1   131]
 [    9    40    79   197     0   389     1    23     7    61   106]
 [   34    77   102   165     1   639     0    60   124     1  1002]]


Accuracy : 

 40.69277251748584


Report : 

               precision    recall  f1-score   support

           0       0.34      0.17      0.23      7789
           1       0.40      0.49      0.44     25786
      

In [37]:
import tkinter as tk
import matplotlib.pyplot as plt
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg
#
# tkinter gui
root = tk.Tk()
canvas1 = tk.Canvas(root, width=1250, height=650)
canvas1.pack()

#labels and input boxes
label0 = tk.Label(root,text="PATIENT LENGTH OF STAY PREDICTION")#.place(x=150,y=30)
canvas1.create_window(600,30,window=label0)
label0.config(font=("Times",25))

# # 1
label1 = tk.Label(root,text="case_id").place(x=50,y=100)
canvas1.create_window(30,100,window=label1)
#label1.config(font=("Times",18))
#
entry1 = tk.Entry(root)
canvas1.create_window(360,100,window=entry1)
entry1.config(font=("Times",18))
#
# # 2
label2 = tk.Label(root,text="Hospital_code").place(x=50,y=130)
canvas1.create_window(30,130,window=label2)
#label2.config(font=("Times",18))

entry2 = tk.Entry(root)
canvas1.create_window(360,130,window=entry2)
entry2.config(font=("Times",18))
#
label3 = tk.Label(root,text="Hospital_type_code").place(x=50,y=160)
canvas1.create_window(30,160,window=label3)
#label3.config(font=("Times",18))

entry3 = tk.Entry(root)
canvas1.create_window(360,160,window=entry3)
entry3.config(font=("Times",18))

label3_0 = tk.Label(root,text="Enter 0 for a, 1 for b, 2 for c, 3 for d, 4 for e, 5 for f, 6 for g Hospital Type Code").place(x=50,y=190)
canvas1.create_window(30,190,window=label3_0)
# # 4
label4 = tk.Label(root,text="City_Code_Hospital").place(x=50,y=240)
canvas1.create_window(30,240,window=label4)
#label4.config(font=("Times",18))

entry4 = tk.Entry(root)
canvas1.create_window(360,240,window=entry4)
entry4.config(font=("Times",18))
#
# # 5
label5= tk.Label(root,text="Available Extra Rooms in Hospital").place(x=50,y=270)
canvas1.create_window(30,270,window=label5)
#label5.config(font=("Times",18))

entry5 = tk.Entry(root)
canvas1.create_window(360,270,window=entry5)
entry5.config(font=("Times",18))
#
# # 6
label6 = tk.Label(root,text="Department").place(x=50,y=300)
canvas1.create_window(30,300,window=label6)
#label6.config(font=("Times",18))

entry6 = tk.Entry(root)
canvas1.create_window(360,300,window=entry6)
entry6.config(font=("Times",18))

label6_0 = tk.Label(root,text="(Enter 0 for TB & Chest disease, 1 for anesthesia, 2 for gynecology, 3 for radiology, 4 for surgery)").place(x=50,y=330)
canvas1.create_window(30,330,window=label6_0)

# # 7
label7 = tk.Label(root,text="Ward_Type").place(x=50,y=380)
canvas1.create_window(30,380,window=label7)
#label7.config(font=("Times",18))

entry7 = tk.Entry(root)
canvas1.create_window(360,380,window=entry7)
entry7.config(font=("Times",18))

label7_0 = tk.Label(root,text="(Enter 0 for P, 1 for Q, 2 for R, 3 for S, 4 for T, 5 for U)" ).place(x=50,y=410)
canvas1.create_window(30,410,window=label7_0)

#
# # 8
label8 = tk.Label(root,text="Ward_Facility_Code").place(x=50,y=460)
canvas1.create_window(30,460,window=label8)
#label8.config(font=("Times",18))

entry8 = tk.Entry(root)
canvas1.create_window(360,460,window=entry8)
entry8.config(font=("Times",18))

label8_0 = tk.Label(root,text="(Enter 0 for A, 1 for B, 2 for C, 3 for D, 4 for E, 5 for F)").place(x=50,y=490)
canvas1.create_window(30,490,window=label8_0)

# # 9
label9 = tk.Label(root,text="Bed_Grade").place(x=50,y=540)
canvas1.create_window(30,540,window=label9)
#label9.config(font=("Times",18))

entry9 = tk.Entry(root)
canvas1.create_window(360,540,window=entry9)
entry9.config(font=("Times",18))
#
# 10
label10 = tk.Label(root,text="patientid").place(x=600,y=100)
canvas1.create_window(600,100,window=label10)
#label10.config(font=("Times",18))

entry10 = tk.Entry(root)
canvas1.create_window(1000,100,window=entry10)
entry10.config(font=("Times",18))
# 10

label11 = tk.Label(root,text="City_Code_Patient").place(x=600,y=130)
canvas1.create_window(600,130,window=label11)
#label11.config(font=("Times",18))

entry11 = tk.Entry(root)
canvas1.create_window(1000,130,window=entry11)
entry11.config(font=("Times",18))

# 11
label12 = tk.Label(root,text="Type_of_Admission").place(x=600,y=160)
canvas1.create_window(600,160,window=label12)
#label12.config(font=("Times",18))

entry12 = tk.Entry(root)
canvas1.create_window(1000,160,window=entry12)
entry12.config(font=("Times",18))

label12_0 = tk.Label(root,text="Enter 0 for Emergency, 1 for Trauma & 2 for Urgent Type Of Admission").place(x=600,y=190)
canvas1.create_window(600,190,window=label12_0)


# 12
label13 = tk.Label(root,text="Severity_of_Illness").place(x=600,y=240)
canvas1.create_window(600,240,window=label13)
#label13.config(font=("Times",18))

entry13 = tk.Entry(root)
canvas1.create_window(1000,240,window=entry13)
entry13.config(font=("Times",18))

label13_0 = tk.Label(root,text="Enter 0 for Extreme, 1 for Minor & 2 for Moderate Severity of illnes").place(x=600,y=270)
canvas1.create_window(600,270,window=label13_0)


# 13
label14 = tk.Label(root,text="Visitors_with_Patient").place(x=600,y=320)
canvas1.create_window(600,320,window=label14)
#label14.config(font=("Times",18))

entry14 = tk.Entry(root)
canvas1.create_window(1000,320,window=entry14)
entry14.config(font=("Times",18))

# 14
label15 = tk.Label(root,text="Age").place(x=600,y=350)
canvas1.create_window(600,350,window=label15)
#label15.config(font=("Times",18))

entry15 = tk.Entry(root)
canvas1.create_window(1000,350,window=entry15)
entry15.config(font=("Times",18))

label15_0 = tk.Label(root,text="Enter rerspective code [0:(0-10), 1:(11-20),2:(21-30),3:(31-40),4:(41-50),5:(51-60),6:(61-70),7:(71-80),8:(81-90),9:(91-100)").place(x=600,y=380)
canvas1.create_window(600,380,window=label15_0)

# 15
label16 = tk.Label(root,text="Admission_Deposit").place(x=600,y=430)
canvas1.create_window(600,430,window=label16)
#label16.config(font=("Times",18))

entry16 = tk.Entry(root)
canvas1.create_window(1000,430,window=entry16)
entry16.config(font=("Times",18))

# 16
label17 = tk.Label(root,text="Available_Extra_Rooms_in_Hospital").place(x=600,y=460)
canvas1.create_window(600,460,window=label17)
#label17.config(font=("Times",18))

entry17 = tk.Entry(root)
canvas1.create_window(1000,460,window=entry17)
entry17.config(font=("Times",18))

def values():
    global case_id
    case_id = float(entry1.get())
    global Hospital_code
    Hospital_code = float(entry2.get())
    global Hospital_type_code
    Hospital_type_code = float(entry3.get())
    global City_Code_Hospital
    City_Code_Hospital = float(entry4.get())
    global Available_Extra_Rooms_in_Hospital
    Available_Extra_Rooms_in_Hospital  = float(entry5.get())
    global Department
    Department  = float(entry6.get())
    global Ward_Type
    Ward_Type  = float(entry7.get())
    global Ward_Facility_Code
    Ward_Facility_Code  = float(entry8.get())
    global Bed_Grade
    Bed_Grade  = float(entry9.get())
    global patientid
    patientid = float(entry10.get())
    global City_Code_Patient
    City_Code_Patient = float(entry11.get())
    global Type_of_Admission
    Type_of_Admission = float(entry12.get())
    global Severity_of_Illness
    Severity_of_Illness  = float(entry13.get())
    global Visitors_with_Patient
    Visitors_with_Patient  = float(entry14.get())
    global Age
    Age  = float(entry15.get())
    global Admission_Deposit
    Admission_Deposit  = float(entry16.get())
    global Available_Extra_Rooms_in_Hospita
    Available_Extra_Rooms_in_Hospita = float(entry17.get())
    res = classifier.predict([[case_id, Hospital_code, Hospital_type_code, City_Code_Hospital, \
                               Available_Extra_Rooms_in_Hospital, Department, Ward_Type, Ward_Facility_Code,\
                               Bed_Grade, patientid, City_Code_Patient, Type_of_Admission, Severity_of_Illness, \
                               Visitors_with_Patient, Age, Admission_Deposit,Available_Extra_Rooms_in_Hospita ]])
    if res == 0:
        res="0-10 days"
    elif res == 1:
        res="11-20 days"
    elif res == 2:
        res="21-30 days"
    elif res == 3:
        res="31-40 days"
    elif res == 4:
        res="41-50 days"
    elif res == 5:
        res="51-60 days"
    elif res == 6:
        res="61-70 days"
    elif res == 7:
        res="71-80 days"
    elif res == 8:
        res="81-90 days"
    elif res == 9:
        res="91-100 days"
    else :
        res="more than 100 days"
    prediction_res = ("Result :", res)
    label_prediction = tk.Label(root, text=prediction_res, bg="green").place(x=900, y=550)
    canvas1.create_window(900,550,window=label_prediction)
    #label_prediction.config(font=("Times",18))

button1 = tk.Button(root, text="Predict Length of Patient Stay", command=values, bg='blue')
canvas1.create_window(750,550,window=button1)
button1.config(font=("Times",18))
root.resizable(0,0)
root.mainloop()


Exception in Tkinter callback
Traceback (most recent call last):
  File "c:\users\sheetal\appdata\local\programs\python\python37\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "<ipython-input-37-0f31bf0d8783>", line 228, in values
    Visitors_with_Patient, Age, Admission_Deposit,Available_Extra_Rooms_in_Hospita ]])
  File "c:\users\sheetal\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\_forest.py", line 629, in predict
    proba = self.predict_proba(X)
  File "c:\users\sheetal\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\_forest.py", line 673, in predict_proba
    X = self._validate_X_predict(X)
  File "c:\users\sheetal\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\_forest.py", line 421, in _validate_X_predict
    return self.estimators_[0]._validate_X_predict(X, check_input=True)
  File "c:\users\sheetal\appdata\local\programs\python\python37\lib\site-packages\skle