In [74]:
# import lib
import pandas as pd
import numpy as np
import seaborn as sns
from matplotlib import pyplot as plt 
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, RobustScaler, StandardScaler, MinMaxScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB

In [75]:
df_train = pd.read_csv("E:/ML/AISS/patient_stay_2_1310/train_data.csv")
df_test = pd.read_csv("E:/ML/AISS/patient_stay_2_1310/test_data.csv")
print("train ",df_train.shape, " test ", df_test.shape)
df_train.head(2)

train  (318438, 18)  test  (137057, 17)


case_id  Hospital_code Hospital_type_code  City_Code_Hospital  \
0        1              8                  c                   3   
1        2              2                  c                   5   

  Hospital_region_code  Available Extra Rooms in Hospital    Department  \
0                    Z                                  3  radiotherapy   
1                    Z                                  2  radiotherapy   

  Ward_Type Ward_Facility_Code  Bed Grade  patientid  City_Code_Patient  \
0         R                  F        2.0      31397                7.0   
1         S                  F        2.0      31397                7.0   

  Type of Admission Severity of Illness  Visitors with Patient    Age  \
0         Emergency             Extreme                      2  51-60   
1            Trauma             Extreme                      2  51-60   

   Admission_Deposit   Stay  
0             4911.0   0-10  
1             5954.0  41-50

In [76]:
df_train.corr()

case_id  Hospital_code  \
case_id                            1.000000      -0.043023   
Hospital_code                     -0.043023       1.000000   
City_Code_Hospital                -0.011352       0.128294   
Available Extra Rooms in Hospital  0.042580      -0.059638   
Bed Grade                          0.013702      -0.013739   
patientid                         -0.004150       0.002291   
City_Code_Patient                  0.065196      -0.015530   
Visitors with Patient              0.001309      -0.028500   
Admission_Deposit                 -0.045972       0.045446   

                                   City_Code_Hospital  \
case_id                                     -0.011352   
Hospital_code                                0.128294   
City_Code_Hospital                           1.000000   
Available Extra Rooms in Hospital           -0.045771   
Bed Grade                                   -0.049309   
patientid                                    0.000750   
City_Code_Patient                           -0.023988   
Visitors with Patient                        0.018184   
Admission_Deposit                           -0.034455   

                                   Available Extra Rooms in Hospital  \
case_id                                                     0.042580   
Hospital_code                                              -0.059638   
City_Code_Hospital                                         -0.045771   
Available Extra Rooms in Hospital                           1.000000   
Bed Grade                                                  -0.115868   
patientid                                                   0.000921   
City_Code_Patient                                          -0.009681   
Visitors with Patient                                       0.096714   
Admission_Deposit                                          -0.143739   

                                   Bed Grade  patientid  City_Code_Patient  \
case_id                             0.013702  -0.004150           0.065196   
Hospital_code                      -0.013739   0.002291          -0.015530   
City_Code_Hospital                 -0.049309   0.000750          -0.023988   
Available Extra Rooms in Hospital  -0.115868   0.000921          -0.009681   
Bed Grade                           1.000000   0.001645          -0.008105   
patientid                           0.001645   1.000000           0.002002   
City_Code_Patient                  -0.008105   0.002002           1.000000   
Visitors with Patient               0.088945   0.006889          -0.012074   
Admission_Deposit                   0.073833  -0.000877           0.025837   

                                   Visitors with Patient  Admission_Deposit  
case_id                                         0.001309          -0.045972  
Hospital_code                                  -0.028500           0.045446  
City_Code_Hospital                              0.018184          -0.034455  
Available Extra Rooms in Hospital               0.096714          -0.143739  
Bed Grade                                       0.088945           0.073833  
patientid                                       0.006889          -0.000877  
City_Code_Patient                              -0.012074           0.025837  
Visitors with Patient                           1.000000          -0.150358  
Admission_Deposit                              -0.150358           1.000000

In [77]:
label_encoder = preprocessing.LabelEncoder()

In [78]:
df_train['Stay'] = label_encoder.fit_transform(df_train['Stay'])
stay_train = df_train.Stay

In [79]:
X = df_train.drop("Stay", axis=1)
y = df_test
data = pd.concat([X,y])

In [80]:
print(data.shape)
data.head(2)

(455495, 17)


case_id  Hospital_code Hospital_type_code  City_Code_Hospital  \
0        1              8                  c                   3   
1        2              2                  c                   5   

  Hospital_region_code  Available Extra Rooms in Hospital    Department  \
0                    Z                                  3  radiotherapy   
1                    Z                                  2  radiotherapy   

  Ward_Type Ward_Facility_Code  Bed Grade  patientid  City_Code_Patient  \
0         R                  F        2.0      31397                7.0   
1         S                  F        2.0      31397                7.0   

  Type of Admission Severity of Illness  Visitors with Patient    Age  \
0         Emergency             Extreme                      2  51-60   
1            Trauma             Extreme                      2  51-60   

   Admission_Deposit  
0             4911.0  
1             5954.0

In [81]:
# rename columns
original_col = data.columns
new_col = ['case_id','Hospital_code','Hospital_type_code','City_Code_Hospital','Hospital_region_code','Available_Extra_Rooms_in_Hospital','Department','Ward_Type','Ward_Facility_Code','Bed_Grade','patientid','City_Code_Patient','Type_of_Admission','Severity_of_Illness','Visitors_with_Patient','Age','Admission_Deposit']                                                                                                               
data =data.rename(columns=dict(zip(original_col, new_col)))
print(data.shape)
#print(data.head())

(455495, 17)


In [82]:
data.isnull().sum()

case_id                                 0
Hospital_code                           0
Hospital_type_code                      0
City_Code_Hospital                      0
Hospital_region_code                    0
Available_Extra_Rooms_in_Hospital       0
Department                              0
Ward_Type                               0
Ward_Facility_Code                      0
Bed_Grade                             148
patientid                               0
City_Code_Patient                    6689
Type_of_Admission                       0
Severity_of_Illness                     0
Visitors_with_Patient                   0
Age                                     0
Admission_Deposit                       0
dtype: int64

In [83]:
print(data.Bed_Grade.mode())
data.Bed_Grade = data.Bed_Grade.fillna(2.0)

print(data.City_Code_Patient.mode())
data.City_Code_Patient = data.City_Code_Patient.fillna(8.0)

0    2.0
dtype: float64
0    8.0
dtype: float64


In [84]:
print(data.isnull().sum())
data.shape

case_id                              0
Hospital_code                        0
Hospital_type_code                   0
City_Code_Hospital                   0
Hospital_region_code                 0
Available_Extra_Rooms_in_Hospital    0
Department                           0
Ward_Type                            0
Ward_Facility_Code                   0
Bed_Grade                            0
patientid                            0
City_Code_Patient                    0
Type_of_Admission                    0
Severity_of_Illness                  0
Visitors_with_Patient                0
Age                                  0
Admission_Deposit                    0
dtype: int64


(455495, 17)

In [85]:
fig_dims = (30, 30)
fig, ax = plt.subplots(figsize=fig_dims)
hist = data.hist(bins=20, ax=ax) 
plt.savefig("hist.png")
#plt.show()
plt.close()

c:\users\sheetal\appdata\local\programs\python\python37\lib\site-packages\IPython\core\interactiveshell.py:3296: UserWarning: To output multiple subplots, the figure containing the passed axes is being cleared
  exec(code_obj, self.user_global_ns, self.user_ns)


In [86]:
data.dtypes

case_id                                int64
Hospital_code                          int64
Hospital_type_code                    object
City_Code_Hospital                     int64
Hospital_region_code                  object
Available_Extra_Rooms_in_Hospital      int64
Department                            object
Ward_Type                             object
Ward_Facility_Code                    object
Bed_Grade                            float64
patientid                              int64
City_Code_Patient                    float64
Type_of_Admission                     object
Severity_of_Illness                   object
Visitors_with_Patient                  int64
Age                                   object
Admission_Deposit                    float64
dtype: object

Outliers present in 

        City_Code_Patient 
        Available_Extra_Rooms_in_Hospital 
        Visitors_with_Patient
        admission_deposit

In [87]:
data.head(3)

case_id  Hospital_code Hospital_type_code  City_Code_Hospital  \
0        1              8                  c                   3   
1        2              2                  c                   5   
2        3             10                  e                   1   

  Hospital_region_code  Available_Extra_Rooms_in_Hospital    Department  \
0                    Z                                  3  radiotherapy   
1                    Z                                  2  radiotherapy   
2                    X                                  2    anesthesia   

  Ward_Type Ward_Facility_Code  Bed_Grade  patientid  City_Code_Patient  \
0         R                  F        2.0      31397                7.0   
1         S                  F        2.0      31397                7.0   
2         S                  E        2.0      31397                7.0   

  Type_of_Admission Severity_of_Illness  Visitors_with_Patient    Age  \
0         Emergency             Extreme                      2  51-60   
1            Trauma             Extreme                      2  51-60   
2            Trauma             Extreme                      2  51-60   

   Admission_Deposit  
0             4911.0  
1             5954.0  
2             4745.0

In [88]:
# data = data.drop("case_id",axis=1)
# data = data.drop("patientid",axis=1)
# print(data.shape)
# data.head(3)

In [89]:
data.dtypes

case_id                                int64
Hospital_code                          int64
Hospital_type_code                    object
City_Code_Hospital                     int64
Hospital_region_code                  object
Available_Extra_Rooms_in_Hospital      int64
Department                            object
Ward_Type                             object
Ward_Facility_Code                    object
Bed_Grade                            float64
patientid                              int64
City_Code_Patient                    float64
Type_of_Admission                     object
Severity_of_Illness                   object
Visitors_with_Patient                  int64
Age                                   object
Admission_Deposit                    float64
dtype: object

In [90]:
fig_dims = (50, 50)
fig, ax = plt.subplots(figsize=fig_dims)
hist = data.hist(bins=20, ax=ax) 
plt.savefig("hist_after_scale.png")
#plt.show()
plt.close()

In [91]:
scaler = RobustScaler()
#scaler = StandardScaler()
#scaler = MinMaxScaler()
data[["Hospital_code","City_Code_Hospital","Available_Extra_Rooms_in_Hospital","Bed_Grade","City_Code_Patient","Visitors_with_Patient","Admission_Deposit"]] =scaler.fit_transform(data[["Hospital_code","City_Code_Hospital","Available_Extra_Rooms_in_Hospital","Bed_Grade","City_Code_Patient","Visitors_with_Patient","Admission_Deposit"]])
# scaling done for : "Hospital_code","City_Code_Hospital","Available_Extra_Rooms_in_Hospital","Bed_Grade",
#                   "City_Code_Patient","Visitors_with_Patient","Admission_Deposit"

In [92]:
# Encode labels in column 'Department'.
data["case_id"]= label_encoder.fit_transform(data["case_id"])
data["patientid"]= label_encoder.fit_transform(data["patientid"])
data['Hospital_code']= label_encoder.fit_transform(data['Hospital_code']) 
data['Hospital_type_code']= label_encoder.fit_transform(data['Hospital_type_code'])
data['City_Code_Hospital']= label_encoder.fit_transform(data['City_Code_Hospital']) 
data['Hospital_region_code']= label_encoder.fit_transform(data['Hospital_region_code']) 
data['Available_Extra_Rooms_in_Hospita']= label_encoder.fit_transform(data['Available_Extra_Rooms_in_Hospital']) 
data['Department']= label_encoder.fit_transform(data['Department']) 
data['Ward_Type']= label_encoder.fit_transform(data['Ward_Type']) 
data['Ward_Facility_Code']= label_encoder.fit_transform(data['Ward_Facility_Code']) 


data['Type_of_Admission']= label_encoder.fit_transform(data['Type_of_Admission']) 
data['Severity_of_Illness']= label_encoder.fit_transform(data['Severity_of_Illness']) 
data['Visitors_with_Patient']= label_encoder.fit_transform(data['Visitors_with_Patient']) 
data['Age']= label_encoder.fit_transform(data['Age']) 

# not encoded : admission_Deposit, Bed_Grade, City_Code_Patient
# column not removed : case_id, patientid

In [93]:
data.head()

case_id  Hospital_code  Hospital_type_code  City_Code_Hospital  \
0        0              7                   2                   2   
1        1              1                   2                   4   
2        2              9                   4                   0   
3        3             25                   1                   1   
4        4             25                   1                   1   

   Hospital_region_code  Available_Extra_Rooms_in_Hospital  Department  \
0                     2                                0.0           3   
1                     2                               -0.5           3   
2                     0                               -0.5           1   
3                     1                               -0.5           3   
4                     1                               -0.5           3   

   Ward_Type  Ward_Facility_Code  Bed_Grade  patientid  City_Code_Patient  \
0          2                   5       -1.0      31396              -0.25   
1          3                   5       -1.0      31396              -0.25   
2          3                   4       -1.0      31396              -0.25   
3          2                   3       -1.0      31396              -0.25   
4          3                   3       -1.0      31396              -0.25   

   Type_of_Admission  Severity_of_Illness  Visitors_with_Patient  Age  \
0                  0                    0                      2    5   
1                  1                    0                      2    5   
2                  1                    0                      2    5   
3                  1                    0                      2    5   
4                  1                    0                      2    5   

   Admission_Deposit  Available_Extra_Rooms_in_Hospita  
0           0.141687                                 3  
1           0.995905                                 2  
2           0.005733                                 2  
3           2.075348                                 2  
4           0.671581                                 2

In [94]:
data.describe()

case_id  Hospital_code  Hospital_type_code  City_Code_Hospital  \
count  455495.00000  455495.000000       455495.000000       455495.000000   
mean   227747.00000      17.326335            1.256501            3.592349   
std    131490.22477       8.634036            1.532773            2.806344   
min         0.00000       0.000000            0.000000            0.000000   
25%    113873.50000      10.000000            0.000000            1.000000   
50%    227747.00000      18.000000            1.000000            4.000000   
75%    341620.50000      25.000000            2.000000            6.000000   
max    455494.00000      31.000000            6.000000           10.000000   

       Hospital_region_code  Available_Extra_Rooms_in_Hospital     Department  \
count         455495.000000                      455495.000000  455495.000000   
mean               0.778461                           0.098070       1.944024   
std                0.753238                           0.583497       0.561536   
min                0.000000                          -1.500000       0.000000   
25%                0.000000                          -0.500000       2.000000   
50%                1.000000                           0.000000       2.000000   
75%                1.000000                           0.500000       2.000000   
max                2.000000                          10.500000       4.000000   

           Ward_Type  Ward_Facility_Code      Bed_Grade      patientid  \
count  455495.000000       455495.000000  455495.000000  455495.000000   
mean        1.888087            3.286956      -0.371785   65785.793563   
std         0.804688            1.689726       0.871929   37968.830850   
min         0.000000            0.000000      -2.000000       0.000000   
25%         1.000000            2.000000      -1.000000   32873.000000   
50%         2.000000            4.000000       0.000000   65734.000000   
75%         2.000000            5.000000       0.000000   98575.500000   
max         5.000000            5.000000       1.000000  131623.000000   

       City_Code_Patient  Type_of_Admission  Severity_of_Illness  \
count      455495.000000      455495.000000        455495.000000   
mean           -0.184871           0.782867             1.374033   
std             1.181183           0.689184             0.768535   
min            -1.750000           0.000000             0.000000   
25%            -1.000000           0.000000             1.000000   
50%             0.000000           1.000000             2.000000   
75%             0.000000           1.000000             2.000000   
max             7.500000           2.000000             2.000000   

       Visitors_with_Patient            Age  Admission_Deposit  \
count          455495.000000  455495.000000      455495.000000   
mean                3.283887       4.126757           0.114197   
std                 1.763101       1.889698           0.888601   
min                 0.000000       0.000000          -2.406224   
25%                 2.000000       3.000000          -0.453726   
50%                 3.000000       4.000000           0.000000   
75%                 4.000000       5.000000           0.546274   
max                28.000000       9.000000           5.882064   

       Available_Extra_Rooms_in_Hospita  
count                     455495.000000  
mean                           3.196059  
std                            1.165920  
min                            0.000000  
25%                            2.000000  
50%                            3.000000  
75%                            4.000000  
max                           17.000000

In [95]:
data.shape

(455495, 18)

In [96]:
data = data.drop("Hospital_region_code", axis=1)
#data = data.drop("Ward_Facility_Code", axis=1)
#data = data.drop("Type_of_Admission", axis=1)
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 455495 entries, 0 to 137056
Data columns (total 17 columns):
case_id                              455495 non-null int64
Hospital_code                        455495 non-null int64
Hospital_type_code                   455495 non-null int32
City_Code_Hospital                   455495 non-null int64
Available_Extra_Rooms_in_Hospital    455495 non-null float64
Department                           455495 non-null int32
Ward_Type                            455495 non-null int32
Ward_Facility_Code                   455495 non-null int32
Bed_Grade                            455495 non-null float64
patientid                            455495 non-null int64
City_Code_Patient                    455495 non-null float64
Type_of_Admission                    455495 non-null int32
Severity_of_Illness                  455495 non-null int32
Visitors_with_Patient                455495 non-null int64
Age                                  455495 non-null int3

### preprocessing of df (train_data) ends here

In [97]:
data_train = data.iloc[:318438]
data_test = data.iloc[318438:]

In [98]:
# X = data_train.values
# test = data_test.values to find y_pred
# y = survived_train.values

X = data_train.values
test = data_test.values
y = stay_train.values

In [99]:
# Instantiate model and fit to data
clf = RandomForestClassifier(n_estimators = 50)
clf.fit(X, y)

GaussianNB(priors=None, var_smoothing=1e-09)

In [100]:
# Make predictions and store in 'Survived' column of df_test
Y_pred = model.predict(test)
df_test['Stay'] = Y_pred

noww y_test is ready

In [101]:
print(df_train.shape)
print(df_test.shape)

(318438, 18)
(137057, 18)


In [102]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.33, random_state=42,stratify=y)

In [103]:
classifier = RandomForestClassifier(n_estimators = 50)
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

In [104]:
# calculate accuracy

from sklearn.metrics import confusion_matrix, accuracy_score, classification_report


print("\n\nConfusion Matrix: \n\n", confusion_matrix(y_test, y_pred))
print ("\n\nAccuracy : \n\n", accuracy_score(y_test,y_pred)*100)
print("\n\nReport : \n\n", classification_report(y_test, y_pred))



Confusion Matrix: 

 [[    0  2166  5623     0     0     0     0     0     0     0     0]
 [    0  6237 19544     4     0     1     0     0     0     0     0]
 [    0  4999 23803    26     0    39     0     0     0     0     5]
 [    0  3681 14432    44     0    33     0     0     0     0    13]
 [    0   742  3088    10     0    16     0     0     0     0    19]
 [    0  2314  8923   142     0   132     0     0     0     0    45]
 [    0   136   739     8     0    17     0     0     0     0     6]
 [    0   620  2459    90     0   125     0     0     0     0    90]
 [    0   316  1016    96     0   139     0     0     0     0    30]
 [    0   128   647    16     0    68     0     0     0     0    53]
 [    0   349   951   191     0   370     0     0     0     0   344]]


Accuracy : 

 29.081219964790407


Report : 

               precision    recall  f1-score   support

           0       0.00      0.00      0.00      7789
           1       0.29      0.24      0.26     25786
     

c:\users\sheetal\appdata\local\programs\python\python37\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [105]:
classifier.feature_importances_

array([0.14828137, 0.04382787, 0.01875632, 0.02437697, 0.03141363,
       0.03016662, 0.03198897, 0.01742568, 0.03411872, 0.14432582,
       0.07208361, 0.02260402, 0.03248012, 0.08597875, 0.0777008 ,
       0.15343097, 0.03103975])

In [106]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 455495 entries, 0 to 137056
Data columns (total 17 columns):
case_id                              455495 non-null int64
Hospital_code                        455495 non-null int64
Hospital_type_code                   455495 non-null int32
City_Code_Hospital                   455495 non-null int64
Available_Extra_Rooms_in_Hospital    455495 non-null float64
Department                           455495 non-null int32
Ward_Type                            455495 non-null int32
Ward_Facility_Code                   455495 non-null int32
Bed_Grade                            455495 non-null float64
patientid                            455495 non-null int64
City_Code_Patient                    455495 non-null float64
Type_of_Admission                    455495 non-null int32
Severity_of_Illness                  455495 non-null int32
Visitors_with_Patient                455495 non-null int64
Age                                  455495 non-null int3