In [1]:
# import lib
import pandas as pd
import numpy as np
import seaborn as sns
from matplotlib import pyplot as plt 
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, RobustScaler, StandardScaler, MinMaxScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB

In [2]:
df_train = pd.read_csv("E:/ML/AISS/patient_stay_2_1310/train_data.csv")
df_test = pd.read_csv("E:/ML/AISS/patient_stay_2_1310/test_data.csv")
print("train ",df_train.shape, " test ", df_test.shape)
df_train.head(2)

train  (318438, 18)  test  (137057, 17)


case_id  Hospital_code Hospital_type_code  City_Code_Hospital  \
0        1              8                  c                   3   
1        2              2                  c                   5   

  Hospital_region_code  Available Extra Rooms in Hospital    Department  \
0                    Z                                  3  radiotherapy   
1                    Z                                  2  radiotherapy   

  Ward_Type Ward_Facility_Code  Bed Grade  patientid  City_Code_Patient  \
0         R                  F        2.0      31397                7.0   
1         S                  F        2.0      31397                7.0   

  Type of Admission Severity of Illness  Visitors with Patient    Age  \
0         Emergency             Extreme                      2  51-60   
1            Trauma             Extreme                      2  51-60   

   Admission_Deposit   Stay  
0             4911.0   0-10  
1             5954.0  41-50

In [25]:
df_train.Stay.value_counts()

2     87491
1     78139
3     55159
5     35018
0     23604
4     11743
7     10254
10     6683
8      4838
9      2765
6      2744
Name: Stay, dtype: int64

In [39]:
count_class_2, count_class_1, count_class_3, count_class_5, count_class_0, count_class_4,\
count_class_7, count_class_10, count_class_8, count_class_9, count_class_6 = df_train['Stay'].value_counts()
print(df_train['Stay'].value_counts())


print("_ _ _ _ _ _ _ _ _")
#Divide by class

df_class_0 =  df_train[df_train['Stay'] == 0]
df_class_1 = df_train[df_train['Stay'] == 1]
df_class_2 = df_train[df_train['Stay'] == 2]
df_class_3 = df_train[df_train['Stay'] == 3]
df_class_4 = df_train[df_train['Stay'] == 4]
df_class_5 = df_train[df_train['Stay'] == 5]
df_class_6 = df_train[df_train['Stay'] == 6]
df_class_7 = df_train[df_train['Stay'] == 7]
df_class_8 = df_train[df_train['Stay'] == 8]
df_class_9 = df_train[df_train['Stay'] == 9]
df_class_10 = df_train[df_train['Stay'] == 10]
print(df_class_2.shape)
df_class_0_over = df_class_0.sample(count_class_2, replace=True)
df_class_1_over = df_class_1.sample(count_class_2, replace=True)
df_class_2_over = df_class_2.sample(count_class_2, replace=True)
df_class_3_over = df_class_3.sample(count_class_2, replace=True)
df_class_4_over = df_class_4.sample(count_class_2, replace=True)
df_class_5_over = df_class_5.sample(count_class_2, replace=True)
df_class_6_over = df_class_6.sample(count_class_2, replace=True)
df_class_7_over = df_class_7.sample(count_class_2, replace=True)
df_class_8_over = df_class_8.sample(count_class_2, replace=True)
df_class_9_over = df_class_9.sample(count_class_2, replace=True)
df_class_10_over = df_class_10.sample(count_class_2, replace=True)


df_test_over = pd.concat([df_class_0_over, df_class_1_over, df_class_2_over, df_class_3_over, df_class_4_over,\
                          df_class_5_over, df_class_6_over, df_class_7_over, df_class_8_over, df_class_9_over,
                         df_class_10_over], axis=0)

# # print("_ _ _ _ _ _ _ _ _")
# # print('Random over-sampling:')
print(df_test_over['Stay'].value_counts())
# # print("_ _ _ _ _ _ _ _ _")
df_train = df_test_over

2     87491
1     78139
3     55159
5     35018
0     23604
4     11743
7     10254
10     6683
8      4838
9      2765
6      2744
Name: Stay, dtype: int64
_ _ _ _ _ _ _ _ _
(87491, 18)
10    87491
9     87491
8     87491
7     87491
6     87491
5     87491
4     87491
3     87491
2     87491
1     87491
0     87491
Name: Stay, dtype: int64


In [40]:
label_encoder = preprocessing.LabelEncoder()

In [41]:
df_train['Stay'] = label_encoder.fit_transform(df_train['Stay'])
stay_train = df_train.Stay

In [42]:
X = df_train.drop("Stay", axis=1)
y = df_test
data = pd.concat([X,y])

In [43]:
print(data.shape)
data.head(2)

(1099458, 17)


case_id  Hospital_code Hospital_type_code  City_Code_Hospital  \
279783   279784             18                  d                  13   
158083   158084             19                  a                   7   

       Hospital_region_code  Available Extra Rooms in Hospital  Department  \
279783                    Y                                  2  gynecology   
158083                    Y                                  2  gynecology   

       Ward_Type Ward_Facility_Code  Bed Grade  patientid  City_Code_Patient  \
279783         R                  B        2.0     116939                3.0   
158083         R                  C        2.0      40162                8.0   

       Type of Admission Severity of Illness  Visitors with Patient    Age  \
279783         Emergency            Moderate                      3  21-30   
158083         Emergency               Minor                      2  51-60   

        Admission_Deposit  
279783             3212.0  
158083             5087.0

In [44]:
# rename columns
original_col = data.columns
new_col = ['case_id','Hospital_code','Hospital_type_code','City_Code_Hospital','Hospital_region_code','Available_Extra_Rooms_in_Hospital','Department','Ward_Type','Ward_Facility_Code','Bed_Grade','patientid','City_Code_Patient','Type_of_Admission','Severity_of_Illness','Visitors_with_Patient','Age','Admission_Deposit']                                                                                                               
data =data.rename(columns=dict(zip(original_col, new_col)))
print(data.shape)
#print(data.head())

(1099458, 17)


In [45]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1099458 entries, 279783 to 137056
Data columns (total 17 columns):
case_id                              1099458 non-null int64
Hospital_code                        1099458 non-null int64
Hospital_type_code                   1099458 non-null object
City_Code_Hospital                   1099458 non-null int64
Hospital_region_code                 1099458 non-null object
Available_Extra_Rooms_in_Hospital    1099458 non-null int64
Department                           1099458 non-null object
Ward_Type                            1099458 non-null object
Ward_Facility_Code                   1099458 non-null object
Bed_Grade                            1098960 non-null float64
patientid                            1099458 non-null int64
City_Code_Patient                    1082405 non-null float64
Type_of_Admission                    1099458 non-null object
Severity_of_Illness                  1099458 non-null object
Visitors_with_Patient           

In [46]:
data.isnull().sum()

case_id                                  0
Hospital_code                            0
Hospital_type_code                       0
City_Code_Hospital                       0
Hospital_region_code                     0
Available_Extra_Rooms_in_Hospital        0
Department                               0
Ward_Type                                0
Ward_Facility_Code                       0
Bed_Grade                              498
patientid                                0
City_Code_Patient                    17053
Type_of_Admission                        0
Severity_of_Illness                      0
Visitors_with_Patient                    0
Age                                      0
Admission_Deposit                        0
dtype: int64

In [47]:
print(data.Bed_Grade.mode())
data.Bed_Grade = data.Bed_Grade.fillna(2.0)

print(data.City_Code_Patient.mode())
data.City_Code_Patient = data.City_Code_Patient.fillna(8.0)

0    2.0
dtype: float64
0    8.0
dtype: float64


In [48]:
print(data.isnull().sum())
data.shape

case_id                              0
Hospital_code                        0
Hospital_type_code                   0
City_Code_Hospital                   0
Hospital_region_code                 0
Available_Extra_Rooms_in_Hospital    0
Department                           0
Ward_Type                            0
Ward_Facility_Code                   0
Bed_Grade                            0
patientid                            0
City_Code_Patient                    0
Type_of_Admission                    0
Severity_of_Illness                  0
Visitors_with_Patient                0
Age                                  0
Admission_Deposit                    0
dtype: int64


(1099458, 17)

In [49]:
fig_dims = (30, 30)
fig, ax = plt.subplots(figsize=fig_dims)
hist = data.hist(bins=20, ax=ax) 
plt.savefig("hist.png")
#plt.show()
plt.close()

c:\users\sheetal\appdata\local\programs\python\python37\lib\site-packages\IPython\core\interactiveshell.py:3296: UserWarning: To output multiple subplots, the figure containing the passed axes is being cleared
  exec(code_obj, self.user_global_ns, self.user_ns)


In [50]:
data.dtypes

case_id                                int64
Hospital_code                          int64
Hospital_type_code                    object
City_Code_Hospital                     int64
Hospital_region_code                  object
Available_Extra_Rooms_in_Hospital      int64
Department                            object
Ward_Type                             object
Ward_Facility_Code                    object
Bed_Grade                            float64
patientid                              int64
City_Code_Patient                    float64
Type_of_Admission                     object
Severity_of_Illness                   object
Visitors_with_Patient                  int64
Age                                   object
Admission_Deposit                    float64
dtype: object

Outliers present in 

        City_Code_Patient 
        Available_Extra_Rooms_in_Hospital 
        Visitors_with_Patient
        admission_deposit

In [51]:
data.head(3)

case_id  Hospital_code Hospital_type_code  City_Code_Hospital  \
279783   279784             18                  d                  13   
158083   158084             19                  a                   7   
300367   300368              6                  a                   6   

       Hospital_region_code  Available_Extra_Rooms_in_Hospital    Department  \
279783                    Y                                  2    gynecology   
158083                    Y                                  2    gynecology   
300367                    X                                  4  radiotherapy   

       Ward_Type Ward_Facility_Code  Bed_Grade  patientid  City_Code_Patient  \
279783         R                  B        2.0     116939                3.0   
158083         R                  C        2.0      40162                8.0   
300367         Q                  F        2.0      75716                2.0   

       Type_of_Admission Severity_of_Illness  Visitors_with_Patient    Age  \
279783         Emergency            Moderate                      3  21-30   
158083         Emergency               Minor                      2  51-60   
300367            Trauma            Moderate                      2  51-60   

        Admission_Deposit  
279783             3212.0  
158083             5087.0  
300367             3067.0

In [52]:
# data = data.drop("case_id",axis=1)
# data = data.drop("patientid",axis=1)
# print(data.shape)
# data.head(3)

In [53]:
data.dtypes

case_id                                int64
Hospital_code                          int64
Hospital_type_code                    object
City_Code_Hospital                     int64
Hospital_region_code                  object
Available_Extra_Rooms_in_Hospital      int64
Department                            object
Ward_Type                             object
Ward_Facility_Code                    object
Bed_Grade                            float64
patientid                              int64
City_Code_Patient                    float64
Type_of_Admission                     object
Severity_of_Illness                   object
Visitors_with_Patient                  int64
Age                                   object
Admission_Deposit                    float64
dtype: object

In [54]:
fig_dims = (50, 50)
fig, ax = plt.subplots(figsize=fig_dims)
hist = data.hist(bins=20, ax=ax) 
plt.savefig("hist_after_scale.png")
#plt.show()
plt.close()

In [55]:
scaler = RobustScaler()
#scaler = StandardScaler()
#scaler = MinMaxScaler()
data[["Hospital_code","City_Code_Hospital","Available_Extra_Rooms_in_Hospital","Bed_Grade","City_Code_Patient","Visitors_with_Patient","Admission_Deposit"]] =scaler.fit_transform(data[["Hospital_code","City_Code_Hospital","Available_Extra_Rooms_in_Hospital","Bed_Grade","City_Code_Patient","Visitors_with_Patient","Admission_Deposit"]])
# scaling done for : "Hospital_code","City_Code_Hospital","Available_Extra_Rooms_in_Hospital","Bed_Grade",
#                   "City_Code_Patient","Visitors_with_Patient","Admission_Deposit"

In [56]:
# Encode labels in column 'Department'.
data["case_id"]= label_encoder.fit_transform(data["case_id"])
data["patientid"]= label_encoder.fit_transform(data["patientid"])
data['Hospital_code']= label_encoder.fit_transform(data['Hospital_code']) 
data['Hospital_type_code']= label_encoder.fit_transform(data['Hospital_type_code'])
data['City_Code_Hospital']= label_encoder.fit_transform(data['City_Code_Hospital']) 
data['Hospital_region_code']= label_encoder.fit_transform(data['Hospital_region_code']) 
data['Available_Extra_Rooms_in_Hospita']= label_encoder.fit_transform(data['Available_Extra_Rooms_in_Hospital']) 
data['Department']= label_encoder.fit_transform(data['Department']) 
data['Ward_Type']= label_encoder.fit_transform(data['Ward_Type']) 
data['Ward_Facility_Code']= label_encoder.fit_transform(data['Ward_Facility_Code']) 


data['Type_of_Admission']= label_encoder.fit_transform(data['Type_of_Admission']) 
data['Severity_of_Illness']= label_encoder.fit_transform(data['Severity_of_Illness']) 
data['Visitors_with_Patient']= label_encoder.fit_transform(data['Visitors_with_Patient']) 
data['Age']= label_encoder.fit_transform(data['Age']) 

# not encoded : admission_Deposit, Bed_Grade, City_Code_Patient
# column not removed : case_id, patientid

# case_id 
# Hospital_code 
# Hospital_type_code 
# City_Code_Hospital
# Hospital_region_code
# Available_Extra_Rooms_in_Hospital
# Department
# Ward_Type
# Ward_Facility_Code
# Bed_Grade
# patientid



In [57]:
data.head()

case_id  Hospital_code  Hospital_type_code  City_Code_Hospital  \
279783   216109             17                   3                  10   
158083   122103             18                   0                   6   
300367   232010              5                   0                   5   
278340   215005             22                   0                   5   
221970   171280             30                   2                   2   

        Hospital_region_code  Available_Extra_Rooms_in_Hospital  Department  \
279783                     1                               -0.5           2   
158083                     1                               -0.5           2   
300367                     0                                0.5           3   
278340                     0                                1.5           3   
221970                     2                                0.5           2   

        Ward_Type  Ward_Facility_Code  Bed_Grade  patientid  \
279783          2                   1       -1.0     111901   
158083          2                   2       -1.0      38393   
300367          1                   5       -1.0      72416   
278340          1                   5        1.0      16022   
221970          2                   0       -1.0      68803   

        City_Code_Patient  Type_of_Admission  Severity_of_Illness  \
279783          -1.666667                  0                    2   
158083           0.000000                  0                    1   
300367          -2.000000                  1                    2   
278340           2.333333                  0                    2   
221970           4.333333                  0                    2   

        Visitors_with_Patient  Age  Admission_Deposit  \
279783                      3    2          -1.062454   
158083                      2    5           0.331599   
300367                      2    5          -1.170260   
278340                      3    7          -1.095911   
221970                      3    3           0.187361   

        Available_Extra_Rooms_in_Hospita  
279783                                 2  
158083                                 2  
300367                                 4  
278340                                 6  
221970                                 4

In [58]:
data.describe()

case_id  Hospital_code  Hospital_type_code  City_Code_Hospital  \
count  1.099458e+06   1.099458e+06        1.099458e+06        1.099458e+06   
mean   1.455392e+05   1.768780e+01        1.329773e+00        3.555429e+00   
std    9.263246e+04   8.716355e+00        1.544979e+00        2.810141e+00   
min    0.000000e+00   0.000000e+00        0.000000e+00        0.000000e+00   
25%    7.034700e+04   1.000000e+01        0.000000e+00        1.000000e+00   
50%    1.379370e+05   2.000000e+01        1.000000e+00        4.000000e+00   
75%    2.082660e+05   2.500000e+01        2.000000e+00        6.000000e+00   
max    3.830320e+05   3.100000e+01        6.000000e+00        1.000000e+01   

       Hospital_region_code  Available_Extra_Rooms_in_Hospital    Department  \
count          1.099458e+06                       1.099458e+06  1.099458e+06   
mean           7.995258e-01                       4.258144e-02  1.967498e+00   
std            7.480555e-01                       5.852752e-01  5.549437e-01   
min            0.000000e+00                      -1.500000e+00  0.000000e+00   
25%            0.000000e+00                      -5.000000e-01  2.000000e+00   
50%            1.000000e+00                       0.000000e+00  2.000000e+00   
75%            1.000000e+00                       5.000000e-01  2.000000e+00   
max            2.000000e+00                       1.050000e+01  4.000000e+00   

          Ward_Type  Ward_Facility_Code     Bed_Grade     patientid  \
count  1.099458e+06        1.099458e+06  1.099458e+06  1.099458e+06   
mean   2.000444e+00        3.252168e+00 -3.420213e-01  6.298187e+04   
std    8.172551e-01        1.697226e+00  8.883670e-01  3.641326e+04   
min    0.000000e+00        0.000000e+00 -2.000000e+00  0.000000e+00   
25%    1.000000e+00        2.000000e+00 -1.000000e+00  3.135200e+04   
50%    2.000000e+00        4.000000e+00  0.000000e+00  6.306000e+04   
75%    3.000000e+00        5.000000e+00  0.000000e+00  9.462500e+04   
max    5.000000e+00        5.000000e+00  1.000000e+00  1.259470e+05   

       City_Code_Patient  Type_of_Admission  Severity_of_Illness  \
count       1.099458e+06       1.099458e+06         1.099458e+06   
mean       -2.247617e-01       7.650515e-01         1.345805e+00   
std         1.528768e+00       6.746098e-01         8.035525e-01   
min        -2.333333e+00       0.000000e+00         0.000000e+00   
25%        -1.000000e+00       0.000000e+00         1.000000e+00   
50%         0.000000e+00       1.000000e+00         2.000000e+00   
75%         0.000000e+00       1.000000e+00         2.000000e+00   
max         1.000000e+01       2.000000e+00         2.000000e+00   

       Visitors_with_Patient           Age  Admission_Deposit  \
count           1.099458e+06  1.099458e+06       1.099458e+06   
mean            4.114933e+00  4.284701e+00       1.123897e-01   
std             2.613459e+00  1.905225e+00       8.818158e-01   
min             0.000000e+00  0.000000e+00      -2.112268e+00   
25%             2.000000e+00  3.000000e+00      -4.557621e-01   
50%             4.000000e+00  4.000000e+00       0.000000e+00   
75%             5.000000e+00  6.000000e+00       5.442379e-01   
max             2.800000e+01  9.000000e+00       5.411896e+00   

       Available_Extra_Rooms_in_Hospita  
count                      1.099458e+06  
mean                       3.084866e+00  
std                        1.166810e+00  
min                        0.000000e+00  
25%                        2.000000e+00  
50%                        3.000000e+00  
75%                        4.000000e+00  
max                        1.600000e+01

In [61]:
# data.shape
df_train.shape

(962401, 18)

In [60]:
data = data.drop("Hospital_region_code", axis=1)
#data = data.drop("Ward_Facility_Code", axis=1)
#data = data.drop("Type_of_Admission", axis=1)
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1099458 entries, 279783 to 137056
Data columns (total 17 columns):
case_id                              1099458 non-null int64
Hospital_code                        1099458 non-null int64
Hospital_type_code                   1099458 non-null int32
City_Code_Hospital                   1099458 non-null int64
Available_Extra_Rooms_in_Hospital    1099458 non-null float64
Department                           1099458 non-null int32
Ward_Type                            1099458 non-null int32
Ward_Facility_Code                   1099458 non-null int32
Bed_Grade                            1099458 non-null float64
patientid                            1099458 non-null int64
City_Code_Patient                    1099458 non-null float64
Type_of_Admission                    1099458 non-null int32
Severity_of_Illness                  1099458 non-null int32
Visitors_with_Patient                1099458 non-null int64
Age                                  

### preprocessing of df (train_data) ends here

In [62]:
data_train = data.iloc[:962401]
data_test = data.iloc[962401:]

In [63]:
# X = data_train.values
# test = data_test.values to find y_pred
# y = survived_train.values

X = data_train.values
test = data_test.values
y = stay_train.values

In [64]:
# Instantiate model and fit to data
clf = RandomForestClassifier(n_estimators = 50)
clf.fit(X, y)

RandomForestClassifier(n_estimators=50)

In [65]:
# Make predictions and store in 'Survived' column of df_test
Y_pred = clf.predict(test)
df_test['Stay'] = Y_pred

noww y_test is ready

In [66]:
print(df_train.shape)
print(df_test.shape)

(962401, 18)
(137057, 18)


In [67]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.33, random_state=42,stratify=y)


In [68]:
classifier = RandomForestClassifier(n_estimators = 50)
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

In [69]:
# calculate accuracy

from sklearn.metrics import confusion_matrix, accuracy_score, classification_report


print("\n\nConfusion Matrix: \n\n", confusion_matrix(y_test, y_pred))
print ("\n\nAccuracy : \n\n", accuracy_score(y_test,y_pred)*100)
print("\n\nReport : \n\n", classification_report(y_test, y_pred))



Confusion Matrix: 

 [[27350   765   541   119    36    47     1     8     1     2     2]
 [ 2130 20783  3869  1046   278   648     9    75    15     2    17]
 [ 1636  4159 20746  1301   509   365    25    58    49     5    19]
 [  686  1605  2698 21129   278  2153    14   195    54     8    52]
 [   25    41    39    16 28744     7     0     0     0     0     0]
 [  203   268   446   920    78 26342    15   265   205    20   110]
 [    0     0     0     0     0     0 28873     0     0     0     0]
 [    4     4     6    12     0    53     0 28783     2     0     8]
 [    0     0     0     0     0     0     0     0 28872     0     0]
 [    0     0     0     0     0     0     0     0     0 28872     0]
 [    0     0     0     0     0     0     0     0     2     0 28870]]


Accuracy : 

 91.11157991517446


Report : 

               precision    recall  f1-score   support

           0       0.85      0.95      0.90     28872
           1       0.75      0.72      0.74     28872
      

In [70]:
print(X_train.shape, y_train.shape, X_test.shape, y_test.shape, y_pred.shape)
print(df_train.shape)
print(df_test.shape)

(644808, 17) (644808,) (317593, 17) (317593,) (317593,)
(962401, 18)
(137057, 18)
