In [1]:
# import lib
import pandas as pd
import numpy as np
import seaborn as sns
from matplotlib import pyplot as plt 
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, RobustScaler, StandardScaler, MinMaxScaler
from sklearn.ensemble import AdaBoostClassifier

In [2]:
df_train = pd.read_csv("E:/ML/AISS/patient_stay_2_1310/train_data.csv")
df_test = pd.read_csv("E:/ML/AISS/patient_stay_2_1310/test_data.csv")
print("train ",df_train.shape, " test ", df_test.shape)
df_train.head(2)

train  (318438, 18)  test  (137057, 17)


case_id  Hospital_code Hospital_type_code  City_Code_Hospital  \
0        1              8                  c                   3   
1        2              2                  c                   5   

  Hospital_region_code  Available Extra Rooms in Hospital    Department  \
0                    Z                                  3  radiotherapy   
1                    Z                                  2  radiotherapy   

  Ward_Type Ward_Facility_Code  Bed Grade  patientid  City_Code_Patient  \
0         R                  F        2.0      31397                7.0   
1         S                  F        2.0      31397                7.0   

  Type of Admission Severity of Illness  Visitors with Patient    Age  \
0         Emergency             Extreme                      2  51-60   
1            Trauma             Extreme                      2  51-60   

   Admission_Deposit   Stay  
0             4911.0   0-10  
1             5954.0  41-50

In [3]:
df_train.corr()

case_id  Hospital_code  \
case_id                            1.000000      -0.043023   
Hospital_code                     -0.043023       1.000000   
City_Code_Hospital                -0.011352       0.128294   
Available Extra Rooms in Hospital  0.042580      -0.059638   
Bed Grade                          0.013702      -0.013739   
patientid                         -0.004150       0.002291   
City_Code_Patient                  0.065196      -0.015530   
Visitors with Patient              0.001309      -0.028500   
Admission_Deposit                 -0.045972       0.045446   

                                   City_Code_Hospital  \
case_id                                     -0.011352   
Hospital_code                                0.128294   
City_Code_Hospital                           1.000000   
Available Extra Rooms in Hospital           -0.045771   
Bed Grade                                   -0.049309   
patientid                                    0.000750   
City_Code_Patient                           -0.023988   
Visitors with Patient                        0.018184   
Admission_Deposit                           -0.034455   

                                   Available Extra Rooms in Hospital  \
case_id                                                     0.042580   
Hospital_code                                              -0.059638   
City_Code_Hospital                                         -0.045771   
Available Extra Rooms in Hospital                           1.000000   
Bed Grade                                                  -0.115868   
patientid                                                   0.000921   
City_Code_Patient                                          -0.009681   
Visitors with Patient                                       0.096714   
Admission_Deposit                                          -0.143739   

                                   Bed Grade  patientid  City_Code_Patient  \
case_id                             0.013702  -0.004150           0.065196   
Hospital_code                      -0.013739   0.002291          -0.015530   
City_Code_Hospital                 -0.049309   0.000750          -0.023988   
Available Extra Rooms in Hospital  -0.115868   0.000921          -0.009681   
Bed Grade                           1.000000   0.001645          -0.008105   
patientid                           0.001645   1.000000           0.002002   
City_Code_Patient                  -0.008105   0.002002           1.000000   
Visitors with Patient               0.088945   0.006889          -0.012074   
Admission_Deposit                   0.073833  -0.000877           0.025837   

                                   Visitors with Patient  Admission_Deposit  
case_id                                         0.001309          -0.045972  
Hospital_code                                  -0.028500           0.045446  
City_Code_Hospital                              0.018184          -0.034455  
Available Extra Rooms in Hospital               0.096714          -0.143739  
Bed Grade                                       0.088945           0.073833  
patientid                                       0.006889          -0.000877  
City_Code_Patient                              -0.012074           0.025837  
Visitors with Patient                           1.000000          -0.150358  
Admission_Deposit                              -0.150358           1.000000

In [4]:
label_encoder = preprocessing.LabelEncoder()

In [5]:
df_train['Stay'] = label_encoder.fit_transform(df_train['Stay'])
stay_train = df_train.Stay

In [6]:
X = df_train.drop("Stay", axis=1)
y = df_test
data = pd.concat([X,y])

In [7]:
print(data.shape)
data.head(2)

(455495, 17)


case_id  Hospital_code Hospital_type_code  City_Code_Hospital  \
0        1              8                  c                   3   
1        2              2                  c                   5   

  Hospital_region_code  Available Extra Rooms in Hospital    Department  \
0                    Z                                  3  radiotherapy   
1                    Z                                  2  radiotherapy   

  Ward_Type Ward_Facility_Code  Bed Grade  patientid  City_Code_Patient  \
0         R                  F        2.0      31397                7.0   
1         S                  F        2.0      31397                7.0   

  Type of Admission Severity of Illness  Visitors with Patient    Age  \
0         Emergency             Extreme                      2  51-60   
1            Trauma             Extreme                      2  51-60   

   Admission_Deposit  
0             4911.0  
1             5954.0

In [8]:
# rename columns
original_col = data.columns
new_col = ['case_id','Hospital_code','Hospital_type_code','City_Code_Hospital','Hospital_region_code','Available_Extra_Rooms_in_Hospital','Department','Ward_Type','Ward_Facility_Code','Bed_Grade','patientid','City_Code_Patient','Type_of_Admission','Severity_of_Illness','Visitors_with_Patient','Age','Admission_Deposit']                                                                                                               
data =data.rename(columns=dict(zip(original_col, new_col)))
print(data.shape)

(455495, 17)


In [9]:
data.isnull().sum()

case_id                                 0
Hospital_code                           0
Hospital_type_code                      0
City_Code_Hospital                      0
Hospital_region_code                    0
Available_Extra_Rooms_in_Hospital       0
Department                              0
Ward_Type                               0
Ward_Facility_Code                      0
Bed_Grade                             148
patientid                               0
City_Code_Patient                    6689
Type_of_Admission                       0
Severity_of_Illness                     0
Visitors_with_Patient                   0
Age                                     0
Admission_Deposit                       0
dtype: int64

In [10]:
print(data.Bed_Grade.mode())
data.Bed_Grade = data.Bed_Grade.fillna(2.0)

print(data.City_Code_Patient.mode())
data.City_Code_Patient = data.City_Code_Patient.fillna(8.0)

0    2.0
dtype: float64
0    8.0
dtype: float64


In [11]:
print(data.isnull().sum())
data.shape

case_id                              0
Hospital_code                        0
Hospital_type_code                   0
City_Code_Hospital                   0
Hospital_region_code                 0
Available_Extra_Rooms_in_Hospital    0
Department                           0
Ward_Type                            0
Ward_Facility_Code                   0
Bed_Grade                            0
patientid                            0
City_Code_Patient                    0
Type_of_Admission                    0
Severity_of_Illness                  0
Visitors_with_Patient                0
Age                                  0
Admission_Deposit                    0
dtype: int64


(455495, 17)

In [12]:
fig_dims = (30, 30)
fig, ax = plt.subplots(figsize=fig_dims)
hist = data.hist(bins=20, ax=ax) 
plt.savefig("hist.png")
#plt.show()
plt.close()

c:\users\sheetal\appdata\local\programs\python\python37\lib\site-packages\IPython\core\interactiveshell.py:3296: UserWarning: To output multiple subplots, the figure containing the passed axes is being cleared
  exec(code_obj, self.user_global_ns, self.user_ns)


In [14]:
data.dtypes

case_id                                int64
Hospital_code                          int64
Hospital_type_code                    object
City_Code_Hospital                     int64
Hospital_region_code                  object
Available_Extra_Rooms_in_Hospital      int64
Department                            object
Ward_Type                             object
Ward_Facility_Code                    object
Bed_Grade                            float64
patientid                              int64
City_Code_Patient                    float64
Type_of_Admission                     object
Severity_of_Illness                   object
Visitors_with_Patient                  int64
Age                                   object
Admission_Deposit                    float64
dtype: object

In [15]:
data.head(3)

case_id  Hospital_code Hospital_type_code  City_Code_Hospital  \
0        1              8                  c                   3   
1        2              2                  c                   5   
2        3             10                  e                   1   

  Hospital_region_code  Available_Extra_Rooms_in_Hospital    Department  \
0                    Z                                  3  radiotherapy   
1                    Z                                  2  radiotherapy   
2                    X                                  2    anesthesia   

  Ward_Type Ward_Facility_Code  Bed_Grade  patientid  City_Code_Patient  \
0         R                  F        2.0      31397                7.0   
1         S                  F        2.0      31397                7.0   
2         S                  E        2.0      31397                7.0   

  Type_of_Admission Severity_of_Illness  Visitors_with_Patient    Age  \
0         Emergency             Extreme                      2  51-60   
1            Trauma             Extreme                      2  51-60   
2            Trauma             Extreme                      2  51-60   

   Admission_Deposit  
0             4911.0  
1             5954.0  
2             4745.0

In [16]:
data.dtypes

case_id                                int64
Hospital_code                          int64
Hospital_type_code                    object
City_Code_Hospital                     int64
Hospital_region_code                  object
Available_Extra_Rooms_in_Hospital      int64
Department                            object
Ward_Type                             object
Ward_Facility_Code                    object
Bed_Grade                            float64
patientid                              int64
City_Code_Patient                    float64
Type_of_Admission                     object
Severity_of_Illness                   object
Visitors_with_Patient                  int64
Age                                   object
Admission_Deposit                    float64
dtype: object

In [17]:
fig_dims = (50, 50)
fig, ax = plt.subplots(figsize=fig_dims)
hist = data.hist(bins=20, ax=ax) 
plt.savefig("hist_after_scale.png")
#plt.show()
plt.close()

In [18]:
scaler = RobustScaler()
data[["Hospital_code","City_Code_Hospital","Available_Extra_Rooms_in_Hospital","Bed_Grade","City_Code_Patient","Visitors_with_Patient","Admission_Deposit"]] =scaler.fit_transform(data[["Hospital_code","City_Code_Hospital","Available_Extra_Rooms_in_Hospital","Bed_Grade","City_Code_Patient","Visitors_with_Patient","Admission_Deposit"]])

In [19]:
# Encode labels in column 'Department'.
data["case_id"]= label_encoder.fit_transform(data["case_id"])
data["patientid"]= label_encoder.fit_transform(data["patientid"])
data['Hospital_code']= label_encoder.fit_transform(data['Hospital_code']) 
data['Hospital_type_code']= label_encoder.fit_transform(data['Hospital_type_code'])
data['City_Code_Hospital']= label_encoder.fit_transform(data['City_Code_Hospital']) 
data['Hospital_region_code']= label_encoder.fit_transform(data['Hospital_region_code']) 
data['Available_Extra_Rooms_in_Hospita']= label_encoder.fit_transform(data['Available_Extra_Rooms_in_Hospital']) 
data['Department']= label_encoder.fit_transform(data['Department']) 
data['Ward_Type']= label_encoder.fit_transform(data['Ward_Type']) 
data['Ward_Facility_Code']= label_encoder.fit_transform(data['Ward_Facility_Code']) 


data['Type_of_Admission']= label_encoder.fit_transform(data['Type_of_Admission']) 
data['Severity_of_Illness']= label_encoder.fit_transform(data['Severity_of_Illness']) 
data['Visitors_with_Patient']= label_encoder.fit_transform(data['Visitors_with_Patient']) 
data['Age']= label_encoder.fit_transform(data['Age']) 

In [20]:
data.head()

case_id  Hospital_code  Hospital_type_code  City_Code_Hospital  \
0        0              7                   2                   2   
1        1              1                   2                   4   
2        2              9                   4                   0   
3        3             25                   1                   1   
4        4             25                   1                   1   

   Hospital_region_code  Available_Extra_Rooms_in_Hospital  Department  \
0                     2                                0.0           3   
1                     2                               -0.5           3   
2                     0                               -0.5           1   
3                     1                               -0.5           3   
4                     1                               -0.5           3   

   Ward_Type  Ward_Facility_Code  Bed_Grade  patientid  City_Code_Patient  \
0          2                   5       -1.0      31396              -0.25   
1          3                   5       -1.0      31396              -0.25   
2          3                   4       -1.0      31396              -0.25   
3          2                   3       -1.0      31396              -0.25   
4          3                   3       -1.0      31396              -0.25   

   Type_of_Admission  Severity_of_Illness  Visitors_with_Patient  Age  \
0                  0                    0                      2    5   
1                  1                    0                      2    5   
2                  1                    0                      2    5   
3                  1                    0                      2    5   
4                  1                    0                      2    5   

   Admission_Deposit  Available_Extra_Rooms_in_Hospita  
0           0.141687                                 3  
1           0.995905                                 2  
2           0.005733                                 2  
3           2.075348                                 2  
4           0.671581                                 2

In [21]:
data.describe()

case_id  Hospital_code  Hospital_type_code  City_Code_Hospital  \
count  455495.00000  455495.000000       455495.000000       455495.000000   
mean   227747.00000      17.326335            1.256501            3.592349   
std    131490.22477       8.634036            1.532773            2.806344   
min         0.00000       0.000000            0.000000            0.000000   
25%    113873.50000      10.000000            0.000000            1.000000   
50%    227747.00000      18.000000            1.000000            4.000000   
75%    341620.50000      25.000000            2.000000            6.000000   
max    455494.00000      31.000000            6.000000           10.000000   

       Hospital_region_code  Available_Extra_Rooms_in_Hospital     Department  \
count         455495.000000                      455495.000000  455495.000000   
mean               0.778461                           0.098070       1.944024   
std                0.753238                           0.583497       0.561536   
min                0.000000                          -1.500000       0.000000   
25%                0.000000                          -0.500000       2.000000   
50%                1.000000                           0.000000       2.000000   
75%                1.000000                           0.500000       2.000000   
max                2.000000                          10.500000       4.000000   

           Ward_Type  Ward_Facility_Code      Bed_Grade      patientid  \
count  455495.000000       455495.000000  455495.000000  455495.000000   
mean        1.888087            3.286956      -0.371785   65785.793563   
std         0.804688            1.689726       0.871929   37968.830850   
min         0.000000            0.000000      -2.000000       0.000000   
25%         1.000000            2.000000      -1.000000   32873.000000   
50%         2.000000            4.000000       0.000000   65734.000000   
75%         2.000000            5.000000       0.000000   98575.500000   
max         5.000000            5.000000       1.000000  131623.000000   

       City_Code_Patient  Type_of_Admission  Severity_of_Illness  \
count      455495.000000      455495.000000        455495.000000   
mean           -0.184871           0.782867             1.374033   
std             1.181183           0.689184             0.768535   
min            -1.750000           0.000000             0.000000   
25%            -1.000000           0.000000             1.000000   
50%             0.000000           1.000000             2.000000   
75%             0.000000           1.000000             2.000000   
max             7.500000           2.000000             2.000000   

       Visitors_with_Patient            Age  Admission_Deposit  \
count          455495.000000  455495.000000      455495.000000   
mean                3.283887       4.126757           0.114197   
std                 1.763101       1.889698           0.888601   
min                 0.000000       0.000000          -2.406224   
25%                 2.000000       3.000000          -0.453726   
50%                 3.000000       4.000000           0.000000   
75%                 4.000000       5.000000           0.546274   
max                28.000000       9.000000           5.882064   

       Available_Extra_Rooms_in_Hospita  
count                     455495.000000  
mean                           3.196059  
std                            1.165920  
min                            0.000000  
25%                            2.000000  
50%                            3.000000  
75%                            4.000000  
max                           17.000000

In [22]:
data.shape

(455495, 18)

In [23]:
data = data.drop("Hospital_region_code", axis=1)
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 455495 entries, 0 to 137056
Data columns (total 17 columns):
case_id                              455495 non-null int64
Hospital_code                        455495 non-null int64
Hospital_type_code                   455495 non-null int32
City_Code_Hospital                   455495 non-null int64
Available_Extra_Rooms_in_Hospital    455495 non-null float64
Department                           455495 non-null int32
Ward_Type                            455495 non-null int32
Ward_Facility_Code                   455495 non-null int32
Bed_Grade                            455495 non-null float64
patientid                            455495 non-null int64
City_Code_Patient                    455495 non-null float64
Type_of_Admission                    455495 non-null int32
Severity_of_Illness                  455495 non-null int32
Visitors_with_Patient                455495 non-null int64
Age                                  455495 non-null int3

In [24]:
data_train = data.iloc[:318438]
data_test = data.iloc[318438:]

In [25]:
X = data_train.values
test = data_test.values
y = stay_train.values

In [26]:
# Instantiate model and fit to data
lr = [0.05, 0.25, 0.50, 0.75, 1.0]

for learning_rate in lr:
    clf = AdaBoostClassifier(n_estimators=50, learning_rate = learning_rate)
    clf.fit(X, y)
    
    print("Learning rate: ", learning_rate)
    print("Accuracy score (training): {0:.3f}".format(clf.score(X, y)))
    print("Accuracy score (validation): {0:.3f}".format(clf.score(X, y)))

Learning rate:  0.05
Accuracy score (training): 0.341
Accuracy score (validation): 0.341
Learning rate:  0.25
Accuracy score (training): 0.358
Accuracy score (validation): 0.358
Learning rate:  0.5
Accuracy score (training): 0.366
Accuracy score (validation): 0.366
Learning rate:  0.75
Accuracy score (training): 0.373
Accuracy score (validation): 0.373
Learning rate:  1.0
Accuracy score (training): 0.372
Accuracy score (validation): 0.372


In [27]:
# Make predictions and store in 'Survived' column of df_test
clf = AdaBoostClassifier(n_estimators=50, learning_rate=1)
clf.fit(X, y)

Y_pred = clf.predict(test)
df_test['Stay'] = Y_pred

In [28]:
print(df_train.shape)
print(df_test.shape)

(318438, 18)
(137057, 18)


In [29]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.33, random_state=42,stratify=y)

In [30]:
classifier = AdaBoostClassifier(n_estimators=50, learning_rate=1)
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

In [31]:
# calculate accuracy

from sklearn.metrics import confusion_matrix, accuracy_score, classification_report


print("\n\nConfusion Matrix: \n\n", confusion_matrix(y_test, y_pred))
print ("\n\nAccuracy : \n\n", accuracy_score(y_test,y_pred)*100)
print("\n\nReport : \n\n", classification_report(y_test, y_pred))



Confusion Matrix: 

 [[  778  3476  3315   208     1    11     0     0     0     0     0]
 [ 1222 10293 11530  1673     0  1017     0     2    31     0    18]
 [ 1126  7500 17907  1813     0   457     0     2    30     0    37]
 [  480  3343  6938  3699     4  3611     0     1    58     2    67]
 [  177   828  2130   395     1   281     0     1    24     0    38]
 [  107  1016  1982  2795     1  5374     0     6    73     1   201]
 [   34   135   437   133     0   134     0     0     9     0    24]
 [   31   265   381   844     0  1597     0     2    48     1   215]
 [   14    64    76    97     0  1168     0     5    37     0   136]
 [    7    50   105   206     0   412     0     4    10     0   118]
 [   10   109   142   152     0  1058     0     3    36     0   695]]


Accuracy : 

 36.90916876814008


c:\users\sheetal\appdata\local\programs\python\python37\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))




Report : 

               precision    recall  f1-score   support

           0       0.20      0.10      0.13      7789
           1       0.38      0.40      0.39     25786
           2       0.40      0.62      0.49     28872
           3       0.31      0.20      0.24     18203
           4       0.14      0.00      0.00      3875
           5       0.36      0.47      0.40     11556
           6       0.00      0.00      0.00       906
           7       0.08      0.00      0.00      3384
           8       0.10      0.02      0.04      1597
           9       0.00      0.00      0.00       912
          10       0.45      0.32      0.37      2205

    accuracy                           0.37    105085
   macro avg       0.22      0.19      0.19    105085
weighted avg       0.33      0.37      0.33    105085

